images:
- name: controller
  newName: ghcr.io/anza-labs/image-builder-controller
  newTag: v0.4.3
namePrefix: image-builder-
namespace: image-builder-system
resources:
- ./config/crd
- ./config/manager
- ./config/rbac
