apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: metrics-reader
  labels:
    app.kubernetes.io/name: image-builder
    app.kubernetes.io/managed-by: kustomize
rules:
- nonResourceURLs:
  - "/metrics"
  verbs:
  - get
