---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  - serviceaccounts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps/finalizers
  - secrets/finalizers
  - serviceaccounts/finalizers
  verbs:
  - update
- apiGroups:
  - ""
  resources:
  - configmaps/status
  - secrets/status
  - serviceaccounts/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - jobs/finalizers
  verbs:
  - update
- apiGroups:
  - batch
  resources:
  - jobs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - image-builder.anza-labs.dev
  resources:
  - images
  - linuxkits
  - mkosis
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - image-builder.anza-labs.dev
  resources:
  - images/finalizers
  - linuxkits/finalizers
  - mkosis/finalizers
  verbs:
  - update
- apiGroups:
  - image-builder.anza-labs.dev
  resources:
  - images/status
  - linuxkits/status
  - mkosis/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  - roles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings/finalizers
  - roles/finalizers
  verbs:
  - update
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings/status
  - roles/status
  verbs:
  - get
  - patch
  - update
